gouvenmentSites = {
	'mdrap': ('Ministerul Dezvoltarii Regionale si Administratiei Publice', 'http://www.mdrap.gov.ro/'),
	'mmediu': ('Ministerul Mediului', 'http://www.mmediu.gov.ro/'),
	'mai': ('Ministerul Afacerilor Interne', 'http://www.mai.gov.ro/'),
	'mae': ('Ministerul Afacerilor Externe', 'http://www.mae.gov.ro/'),
	'mapn': ('Ministerul Apararii Nationale', 'http://www.mapn.gov.ro/'),
	'mfinante': ('Ministerul Finantelor Publice', 'http://www.mfinante.gov.ro/'),
	'mjustitie': ('Ministerul Justitiei', 'http://www.just.gov.ro/'),
	'madr': ('Ministerul Agriculturii si Dezvoltarii Rurale', 'http://www.madr.gov.ro/'),
	'meducatie': ('Ministerul Educatiei Nationale', 'http://www.edu.ro/'),
	'mmjs': ('Ministerul Muncii si Justitiei Sociale', 'http://www.mmuncii.gov.ro/'),
	'meconomie': ('Ministerul Economiei', 'http://www.economie.gov.ro/'),
	'mtransporturi': ('Ministerul Transporturilor', 'http://www.mt.gov.ro/'),
	'mfe': ('Ministerul Fondurilor Europene', 'http://mfe.gov.ro/'),
	'mmaca': ('Ministerul pentru Mediul de Afaceri, Comert si Antreprenoriat', 'http://www.imm.gov.ro/'),
	'msanatate': ('Ministerul Sanatatii', 'http://www.ms.gov.ro/'),
	'mcin': ('Ministerul Culturii si Identitatii Nationale', 'http://www.cultura.ro/culturaro'),
	'mpepaduri': ('Ministerul Apelor si Padurilor', 'http://apepaduri.gov.ro/'),
	'mci': ('Ministerul Cercetarii si Inovarii', 'http://www.research.gov.ro/'),
	'mcsi': ('Ministerul Comunicatiilor si Societatii Informationale', 'http://www.comunicatii.gov.ro/'),
	'mts': ('Ministerul Tineretului si Sportului', 'http://www.mts.gov.ro/'),
	'mturism': ('Ministerul Turismului', 'http://turism.gov.ro/'),
	'mrp': ('Ministerul pentru Romanii de Pretutindeni', 'http://www.mprp.gov.ro/web/'),
	'mrelatii': ('Ministerul pentru Relatii cu Parlamentul', 'http://www.drp.gov.ro/')
}